parameters:
# claroline_claroffline.example.class: Claroline\ClarofflineBundle\Example

services:
# claroline_claroffline.example:
# class: %claroline_claroffline.example.class%
# arguments: [@service_id, "plain_value", %parameter%]
