parameters:
    claroline.manager.creation_manager.class: Claroline\OfflineBundle\Manager\CreationManager
    claroline.synchronisation.up_directory: "%claroline.param.files_directory%/synchronize_up/"
    claroline.synchronisation.down_directory: "%claroline.param.files_directory%/synchronize_down/"

services:
    claroline_offline.creation_manager:
        class: %claroline.manager.creation_manager.class%

    claroline_offline.offline.text:
        class: Claroline\OfflineBundle\Model\Resource\OfflineText
        arguments:
            - Claroline\CoreBundle\Persistence\ObjectManager;
            - Claroline\CoreBundle\Manager\ResourceManager;
        tags:
            -  { name: claroline_offline.offline }
