parameters:
    claroline.manager.creation_manager.class: Claroline\OfflineBundle\Manager\CreationManager

services:
    claroline_offline.creation_manager:
        class: %claroline.manager.creation_manager.class%

    claroline_offline.offline.text:
        class: Claroline\OfflineBundle\Model\Resource\OfflineText
        arguments:
            - Claroline\CoreBundle\Persistence\ObjectManager;
            - Claroline\CoreBundle\Manager\ResourceManager;
        tags:
            -  { name: claroline_offline.offline }
